# This builds and runs the test cluster, the command ends when the cucumber-js command
# ends. The exit code for cucumber-js will be passed back to make.
bdd:
	npm install
	node_modules/.bin/cucumber-js
